openbank:
  useCode: M202200139
  client-id: 03366178-450b-46af-a2bf-8af076571fec
  client-secret: c9b400bd-63dc-45a4-bc84-9d2dad8efa9c
  access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMTAxMDAyOTU2Iiwic2NvcGUiOlsiaW5xdWlyeSIsImxvZ2luIiwidHJhbnNmZXIiXSwiaXNzIjoiaHR0cHM6Ly93d3cub3BlbmJhbmtpbmcub3Iua3IiLCJleHAiOjE2NTEwNDI3OTMsImp0aSI6ImYyZjE1MDRmLTRhZTItNGY5NS1iOTg1LWZmMjNjNmMxMmJkMSJ9.kdpltOUlJxJncygVC9RHutrrWrkcmmDRay0KaMuPDQM
  refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMTAxMDAyOTU2Iiwic2NvcGUiOlsiaW5xdWlyeSIsImxvZ2luIiwidHJhbnNmZXIiXSwiaXNzIjoiaHR0cHM6Ly93d3cub3BlbmJhbmtpbmcub3Iua3IiLCJleHAiOjE2NTE5MDY3OTMsImp0aSI6Ijc3NzFlZDM4LWVjMzItNDczMy04ZGQ5LTE1ZDZjNzJmYzFjNSJ9.rNXwwrlxI7jUrUwu2PBqNMJdEdx4cYGxq-B3yRckI9Y
  user_seq_no: 1101002956

spring:
  application:
    name: openapi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_backend?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bank_admin
    password: 1234

